eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  main:
    allow-bean-definition-overriding: true
feign:
  hystrix:
    enabled: true

