eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ribbon-client
stores:
  ribbon:
    listOfServers: example.com,google.com
ribbon:
  eureka:
    enabled: false
server:
  port: 8769

