eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 5000
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: hiapi-vl
#      serviceId: service-hi
#      url: http://localhost:8762
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
#  prefix: /v1
ribbon:
  eureka:
    enabled: false
hiapi-vl:
  ribbon:
    listOfServers: http://localhost:8762,http://localhost:8763