
spring:
  application:
    name: service-turbine
server:
  port: 8769
turbine:
  aggregator:
    cluster-config: default
  app-config: service-feign,service-ribbon
  cluster-name-expression: new String("default")

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/